### ISSUE TITLE
Change boilerplate HTML - Geocoding

### ISSUE THREAD

**Issue by powersa** [MaptimeSEA/maptimesea.github.io#2]
Considering using the first geocode_on_load.html as the boilerplate example...

Or maybe call out explicitly that they must include jquery

**Comment by mapsam** [comment]
This works for me! We could maybe just add a link to your gist instead, and count the first step as the geocode on load?

**Comment by powersa** [comment]
I think this is is resolved by calling out inclusion of jquery and necessary edits explicitly... take a look, good practice to go from boilerplate

**Comment by mapsam** [comment]
Would it be better to add a comment in the gist near the actual inclusion of jQuery? That way if someone is just seeing the code snippet they'll still have the necessary comments without needing the tutorial to follow along.

**Comment by powersa** [comment]
I'm on that approach, can't really assume that they will follow every step in the tut. :scissors: in and out

**Comment by mapsam** [comment]
Updated the gist: https://gist.github.com/svmatthews/0811545938dd1f68595e

**Comment by mapsam** [comment]
What do you think @powersa? Here's the tut intro now:

> # Build a Geocoder
> 
> To get started, grab an [HTML boilerplate](https://gist.github.com/powersa/36be23aaa647c25c3236) from some of our other meetings and save it to a `.html` file. To view that page in your browser, find the file on your computer and right click it to "open with" whichever browser you prefer.
> 
> ## Making a call to an API
> 
> To make a call to an API, we will use a special function to make an [HTTP](http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol) request. In our case, we're going to use the `$.ajax()` function from the [jQuery](http://jquery.com/) library, which allows us to form a call quite easily.
> 
> <aside><strong>Protip:</strong> You can view the results in your browser simply by visiting the URL! <a href="http://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=500%20Yale%20Avenue%20North,%20Seattle,%20WA%2098109&benchmark=4&format=jsonp">Click here to check it out.</a></aside>
> 
> _Note: There are many javascript libraries that include HTTP request functions and do it quite well. You can also do this in regular javascript, but for the sake of this tutorial the jQuery implementation makes this process much easier._
> 
> Access the jQuery library in your webpage by adding the following within the `<head>` of your file:
> 
> ``` html
> <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
> ```

and so forth.

**Comment by powersa** [comment]
That's money. Cuts out the confusion.

**Comment by mapsam** [comment]
Sweet, going to close this sucker!
