### ISSUE TITLE
update some hyperlinks in the Geocoder tutorial

### ISSUE THREAD

**Issue by mapsam** [MaptimeSEA/maptimesea.github.io#3]
@keum suggested some URL updates:
- [x] Under Census Geocoding API heading, towards the end you talk about Cross Origin Issues (looks like you forgot to add the link or probably going to add the link later tonight , found this link explains it little more but might be overkill.. https://jvaneyck.wordpress.com/2014/01/07/cross-domain-requests-in-javascript/  )
- [x] also right below that where you say "Take a look at the Census page with more information...." maybe this link might be helpful to folks http://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.pdf , I know it's in pdf format but was helpful explaining other parameters. 

@keum if you're interested in updating these yourself, you can edit the tutorial post [**here**](https://github.com/MaptimeSEA/maptimesea.github.io/edit/master/_posts/2015-03-03-gecoding-api.markdown) directly on github (like the cugos site) by adding markdown hyperlinks `[link text](link url)` and committing the changes (_I think it will create a pull request, so don't worry about breaking anything_). I'll get to these later, but figured I'd give you a chance :)

**Comment by keum** [comment]
@svmatthews Thanks Sam..just made the pull request.

**Comment by mapsam** [comment]
Oh hey I guess you're already a contributor to the repo so the changes went through automatically! Nice work!
